name: ExoticGarden
version: 1.6.2
authors: [mrCookieSlime, Goldentoenail]
description: A Slimefun Addon that adds new Plants and dishes to the game
website: http://TheBusyBiscuit.github.io/

main: me.mrCookieSlime.ExoticGarden.ExoticGarden

depend: [Slimefun]
softdepend: [CS-CoreLib]